# ---------- Base ----------
FROM node:20-alpine AS base

# Install dependencies needed for some node packages (like sharp)
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Enable pnpm via Corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

# ---------- Dependencies ----------
FROM base AS deps
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

# ---------- Build ----------
FROM base AS builder

# Define build-time arguments passed by Coolify
ARG COOLIFY_URL
ARG COOLIFY_FQDN
ARG CLOUDFLARE_ACCOUNT_ID
ARG ADMIN_EMAIL
ARG ADMIN_PASSWORD
ARG AUTH_SECRET
ARG FACEBOOK_ACCESS_TOKEN
ARG FACEBOOK_APP_SECRET
ARG FACEBOOK_VERIFY_TOKEN
ARG FACEBOOK_WEBHOOK_URL
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_AUTH_GOOGLE_ID
ARG NEXT_PUBLIC_AUTH_GOOGLE_SECRET
ARG NEXT_PUBLIC_BASE_DOMAIN
ARG NEXT_PUBLIC_BASE_URL
ARG NEXT_PUBLIC_CLOUDINARY_API_KEY
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ARG NEXT_PUBLIC_FACEBOOK_API_VERSION
ARG NEXT_PUBLIC_FACEBOOK_APP_ID
ARG NEXT_PUBLIC_FACEBOOK_CONFIG_ID
ARG NEXT_PUBLIC_FRONTEND_PORT
ARG NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI
ARG NEXT_PUBLIC_PROTOCOL
ARG NEXT_PUBLIC_WIT_API_KEY
ARG VERIFY_TOKEN
ARG WHOIS_JSON_API_KEY
ARG CLOUDFLARE_API_TOKEN
ARG JWT_SECRET
ARG COOLIFY_BUILD_SECRETS_HASH

# Set NEXT_PUBLIC environment variables so they are available during 'next build'
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_AUTH_GOOGLE_ID=$NEXT_PUBLIC_AUTH_GOOGLE_ID
ENV NEXT_PUBLIC_AUTH_GOOGLE_SECRET=$NEXT_PUBLIC_AUTH_GOOGLE_SECRET
ENV NEXT_PUBLIC_BASE_DOMAIN=$NEXT_PUBLIC_BASE_DOMAIN
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_CLOUDINARY_API_KEY=$NEXT_PUBLIC_CLOUDINARY_API_KEY
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=$NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ENV NEXT_PUBLIC_FACEBOOK_API_VERSION=$NEXT_PUBLIC_FACEBOOK_API_VERSION
ENV NEXT_PUBLIC_FACEBOOK_APP_ID=$NEXT_PUBLIC_FACEBOOK_APP_ID
ENV NEXT_PUBLIC_FACEBOOK_CONFIG_ID=$NEXT_PUBLIC_FACEBOOK_CONFIG_ID
ENV NEXT_PUBLIC_FRONTEND_PORT=$NEXT_PUBLIC_FRONTEND_PORT
ENV NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI=$NEXT_PUBLIC_GOOGLE_OAUTH_REDIRECT_URI
ENV NEXT_PUBLIC_PROTOCOL=$NEXT_PUBLIC_PROTOCOL
ENV NEXT_PUBLIC_WIT_API_KEY=$NEXT_PUBLIC_WIT_API_KEY

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js build
RUN pnpm run build

# ---------- Production ----------
FROM base AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

EXPOSE 3000

CMD ["pnpm", "start"]