export const NEPAL_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Lalitpur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Dharan",
  "Butwal",
  "Hetauda",
  "Janakpur",
  "Dhangadhi",
  "Itahari",
  "Nepalgunj",
  "Tulsipur",
  "Siddharthanagar",
  "Damak",
  "Madhyapur Thimi",
  "Kalaiya",
  "Gharauhawa",
  "Gulariya",
  "Tikapur",
  "Lahan",
  "Birendranagar",
  "Bhaktapur",
];

export const SERVICE_CATEGORIES = [
  { slug: "ecommerce-website", name: "Ecommerce Website" },
  { slug: "agency-website", name: "Agency Website" },
  { slug: "booking-website", name: "Booking Website" },
  { slug: "restaurant-website", name: "Restaurant Website" },
  { slug: "clinic-website", name: "Clinic Website" },
  { slug: "dental-website", name: "Dental Website" },
];
